In [1]:
import pandas as pd
import numpy as np

In [2]:
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')

In [3]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [4]:
n_users=ratings.user_id.unique().shape[0]
n_items=ratings.movie_id.unique().shape[0]

In [5]:
print("The number of unique users are:",n_users)
print("The number of unique items are:",n_items)

The number of unique users are: 943
The number of unique items are: 1682

# Create pivot table for user and movie based on ratings

In [6]:
user_movie_pivot_table=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [7]:
user_movie_pivot_table

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Replace nan with 0

In [8]:
user_movie_pivot_table=user_movie_pivot_table.replace(np.nan,0)

In [9]:
user_movie_pivot_table

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Find Cosine Similatity for user and Item

In [10]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(user_movie_pivot_table,metric='cosine')
item_similarity=pairwise_distances(user_movie_pivot_table.T,metric='cosine')

In [11]:
item_similarity

array([[0.00000000e+00, 5.97617822e-01, 6.69755213e-01, ...,
        1.00000000e+00, 9.52816933e-01, 9.52816933e-01],
       [5.97617822e-01, 0.00000000e+00, 7.26930825e-01, ...,
        1.00000000e+00, 9.21700637e-01, 9.21700637e-01],
       [6.69755213e-01, 7.26930825e-01, 2.22044605e-16, ...,
        1.00000000e+00, 1.00000000e+00, 9.03124947e-01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 9.03124947e-01, ...,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [12]:
#mean_user_rating = ratings.mean(axis=1)

In [ ]:
#mean_user_rating_array = mean_user_rating.to_numpy()  # Convert Series to NumPy array

In [ ]:
#mean_user_rating_array

In [ ]:
#mean_user_rating_column_vector = mean_user_rating_array.reshape(-1, 1)  # Reshape to a column vector

In [ ]:
#mean_user_rating_column_vector

In [ ]:
#pred = user_movie_pivot_table.dot(item_similarity) / np.array([np.abs(item_similarity).sum(axis=1)])
#pred = (user_movie_pivot_table.T).dot(item_similarity) / np.array([np.abs(item_similarity).sum(axis=1)])

In [ ]:
#pred

In [13]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        ratings_diff = ratings.sub(mean_user_rating, axis=0)  # Subtract mean from each row
        pred = mean_user_rating.to_numpy()[:, np.newaxis] + np.dot(similarity, ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = np.dot(ratings, similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [14]:
user_prediction = predict(user_movie_pivot_table, user_similarity, type='user')
item_prediction = predict(user_movie_pivot_table, item_similarity, type='item')

In [15]:
item_prediction

array([[0.44627765, 0.475473  , 0.50593755, ..., 0.58815455, 0.5731069 ,
        0.56669645],
       [0.10854432, 0.13295661, 0.12558851, ..., 0.13445801, 0.13657587,
        0.13711081],
       [0.08568497, 0.09169006, 0.08764343, ..., 0.08465892, 0.08976784,
        0.09084451],
       ...,
       [0.03230047, 0.0450241 , 0.04292449, ..., 0.05302764, 0.0519099 ,
        0.05228033],
       [0.15777917, 0.17409459, 0.18900003, ..., 0.19979296, 0.19739388,
        0.20003117],
       [0.24767207, 0.24489212, 0.28263031, ..., 0.34410424, 0.33051406,
        0.33102478]])

### As per User based filtering ,first have to find similarity between the input user and others

In [16]:
input_item=6

In [17]:
item_sim_table=pd.DataFrame(item_similarity)

In [18]:
item_sim_table

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.000000,0.597618,6.697552e-01,0.545062,0.713286,0.883656,0.379021,0.518886,0.503712,0.726065,...,0.964613,1.0,1.000000,1.000000,0.964613,1.0,1.0,1.0,0.952817,0.952817
1,0.597618,0.000000,7.269308e-01,0.497429,0.681164,0.916437,0.616597,0.662998,0.744748,0.828918,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.921701,0.921701
2,0.669755,0.726931,2.220446e-16,0.675134,0.787043,0.893278,0.627079,0.799206,0.726331,0.841896,...,1.000000,1.0,1.000000,1.000000,0.967708,1.0,1.0,1.0,1.000000,0.903125
3,0.545062,0.497429,6.751336e-01,0.000000,0.665761,0.909692,0.510717,0.509764,0.580956,0.747439,...,1.000000,1.0,0.905978,0.905978,0.962391,1.0,1.0,1.0,0.943587,0.924782
4,0.713286,0.681164,7.870434e-01,0.665761,0.000000,0.962701,0.665231,0.740839,0.727552,0.944547,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.905789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1678,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1679,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1680,0.952817,0.921701,1.000000e+00,0.943587,1.000000,1.000000,0.948502,0.917967,0.942640,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.000000,1.000000
1681,0.952817,0.921701,9.031249e-01,0.924782,0.905789,1.000000,0.948502,1.000000,0.928300,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.000000

In [19]:
similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(5).index

In [20]:
similar_input_item

Index([6, 99, 49, 116, 55], dtype='int64')

In [21]:
#4.Convert in to list

similar_item_input=list(similar_input_item)

In [22]:
#5. Using similar_item_input,can select movie id from ratings table
similar_item_userid_list=[]
for sim_item in similar_item_input:
    sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
    similar_item_userid_list.append(sim)

In [23]:
similar_item_userid_list

[[63,
  1,
  90,
  9,
  79,
  409,
  18,
  486,
  198,
  568,
  181,
  662,
  76,
  537,
  590,
  924,
  655,
  773,
  707,
  870,
  806,
  828,
  524,
  936,
  758,
  71],
 [286,
  313,
  233,
  291,
  280,
  320,
  268,
  303,
  311,
  94,
  246,
  254,
  91,
  38,
  23,
  42,
  195,
  293,
  295,
  178,
  10,
  201,
  16,
  385,
  18,
  263,
  130,
  409,
  102,
  301,
  194,
  128,
  417,
  406,
  325,
  298,
  7,
  393,
  5,
  200,
  392,
  262,
  471,
  13,
  407,
  59,
  189,
  339,
  505,
  279,
  330,
  275,
  381,
  497,
  82,
  450,
  276,
  527,
  85,
  472,
  452,
  496,
  215,
  1,
  378,
  487,
  347,
  210,
  588,
  70,
  456,
  426,
  314,
  474,
  553,
  387,
  483,
  230,
  437,
  44,
  620,
  577,
  389,
  542,
  327,
  734,
  373,
  234,
  756,
  416,
  686,
  650,
  642,
  710,
  307,
  537,
  521,
  167,
  308,
  454,
  643,
  504,
  299,
  606,
  545,
  766,
  807,
  712,
  747,
  711,
  436,
  660,
  95,
  815,
  830,
  399,
  786,
  601,
  848,
  705,
  805,
  716,
  764,
  840,
  913,
  222,
  429,
  887,
  843,
  864,
  632,
  453,
  622,
  911,
  174,
  618,
  878,
  847,
  749,
  405,
  693,
  880,
  826,
  881,
  541,
  897,
  804,
  844,
  49,
  922,
  401,
  458,
  758,
  919,
  865,
  862,
  942,
  885,
  934,
  751,
  882,
  846,
  592,
  532,
  763,
  892,
  796,
  290,
  561,
  932,
  927,
  334],
 [222,
  49,
  1,
  318,
  130,
  303,
  210,
  174,
  256,
  43,
  151,
  336,
  345,
  291,
  416,
  393,
  381,
  378,
  405,
  450,
  435,
  398,
  283,
  94,
  472,
  152,
  536,
  293,
  308,
  579,
  361,
  102,
  89,
  487,
  643,
  749,
  453,
  92,
  712,
  290,
  648,
  804,
  796,
  477,
  716,
  642,
  125,
  659,
  881,
  514,
  655,
  684,
  622,
  87,
  497,
  883,
  790,
  417,
  13,
  854,
  305,
  916,
  95,
  798,
  577,
  860,
  566,
  880,
  593,
  682,
  864,
  830,
  299,
  711,
  892,
  145,
  886,
  500,
  618,
  551,
  561],
 [310,
  279,
  187,
  52,
  308,
  360,
  297,
  125,
  49,
  227,
  370,
  257,
  148,
  138,
  306,
  184,
  374,
  14,
  98,
  387,
  158,
  63,
  199,
  468,
  500,
  116,
  10,
  464,
  113,
  79,
  58,
  558,
  473,
  354,
  25,
  196,
  420,
  437,
  136,
  463,
  585,
  535,
  92,
  264,
  185,
  250,
  591,
  334,
  26,
  523,
  483,
  379,
  710,
  654,
  747,
  762,
  474,
  181,
  243,
  798,
  514,
  707,
  537,
  144,
  655,
  234,
  99,
  561,
  884,
  590,
  639,
  286,
  402,
  634,
  699,
  321,
  909,
  592,
  491,
  825,
  651,
  857,
  931,
  711,
  666,
  878,
  728,
  81,
  1,
  201,
  883,
  527,
  23,
  758,
  409,
  936,
  239,
  874,
  794,
  905,
  869,
  940,
  790,
  524,
  363,
  59,
  62,
  458,
  343,
  919,
  829,
  864,
  894,
  503,
  733,
  930,
  303,
  861,
  271,
  13,
  828,
  18,
  268,
  891,
  937],
 [308,
  16,
  216,
  197,
  37,
  137,
  267,
  44,
  251,
  339,
  130,
  343,
  352,
  315,
  248,
  87,
  328,
  293,
  363,
  286,
  303,
  371,
  249,
  269,
  178,
  49,
  142,
  347,
  94,
  246,
  268,
  393,
  195,
  387,
  62,
  327,
  110,
  24,
  296,
  416,
  479,
  177,
  59,
  183,
  425,
  262,
  429,
  118,
  207,
  291,
  109,
  297,
  198,
  218,
  158,
  545,
  405,
  445,
  506,
  23,
  144,
  346,
  524,
  645,
  135,
  650,
  619,
  653,
  551,
  92,
  299,
  559,
  487,
  454,
  417,
  627,
  577,
  756,
  583,
  361,
  466,
  399,
  221,
  442,
  145,
  447,
  846,
  826,
  213,
  655,
  102,
  606,
  250,
  629,
  823,
  632,
  908,
  682,
  805,
  1,
  932,
  854,
  385,
  592,
  548,
  788,
  276,
  378,
  877,
  889,
  186,
  640,
  374,
  883,
  739,
  896,
  897,
  763,
  727,
  880,
  162,
  499,
  8,
  160,
  495,
  201,
  943,
  751,
  621,
  875,
  833,
  844,
  864,
  474,
  916,
  643,
  804,
  497,
  453,
  870,
  435,
  468,
  868,
  618,
  671,
  658,
  561,
  886,
  214]]

In [24]:
#6. Convert all the list as single
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))

In [25]:
similar_item_userid_single_list

[63,
 1,
 90,
 9,
 79,
 409,
 18,
 486,
 198,
 568,
 181,
 662,
 76,
 537,
 590,
 924,
 655,
 773,
 707,
 870,
 806,
 828,
 524,
 936,
 758,
 71,
 286,
 313,
 233,
 291,
 280,
 320,
 268,
 303,
 311,
 94,
 246,
 254,
 91,
 38,
 23,
 42,
 195,
 293,
 295,
 178,
 10,
 201,
 16,
 385,
 18,
 263,
 130,
 409,
 102,
 301,
 194,
 128,
 417,
 406,
 325,
 298,
 7,
 393,
 5,
 200,
 392,
 262,
 471,
 13,
 407,
 59,
 189,
 339,
 505,
 279,
 330,
 275,
 381,
 497,
 82,
 450,
 276,
 527,
 85,
 472,
 452,
 496,
 215,
 1,
 378,
 487,
 347,
 210,
 588,
 70,
 456,
 426,
 314,
 474,
 553,
 387,
 483,
 230,
 437,
 44,
 620,
 577,
 389,
 542,
 327,
 734,
 373,
 234,
 756,
 416,
 686,
 650,
 642,
 710,
 307,
 537,
 521,
 167,
 308,
 454,
 643,
 504,
 299,
 606,
 545,
 766,
 807,
 712,
 747,
 711,
 436,
 660,
 95,
 815,
 830,
 399,
 786,
 601,
 848,
 705,
 805,
 716,
 764,
 840,
 913,
 222,
 429,
 887,
 843,
 864,
 632,
 453,
 622,
 911,
 174,
 618,
 878,
 847,
 749,
 405,
 693,
 880,
 826,
 881,
 541,
 897,
 804,
 844,
 49,
 922,
 401,
 458,
 758,
 919,
 865,
 862,
 942,
 885,
 934,
 751,
 882,
 846,
 592,
 532,
 763,
 892,
 796,
 290,
 561,
 932,
 927,
 334,
 222,
 49,
 1,
 318,
 130,
 303,
 210,
 174,
 256,
 43,
 151,
 336,
 345,
 291,
 416,
 393,
 381,
 378,
 405,
 450,
 435,
 398,
 283,
 94,
 472,
 152,
 536,
 293,
 308,
 579,
 361,
 102,
 89,
 487,
 643,
 749,
 453,
 92,
 712,
 290,
 648,
 804,
 796,
 477,
 716,
 642,
 125,
 659,
 881,
 514,
 655,
 684,
 622,
 87,
 497,
 883,
 790,
 417,
 13,
 854,
 305,
 916,
 95,
 798,
 577,
 860,
 566,
 880,
 593,
 682,
 864,
 830,
 299,
 711,
 892,
 145,
 886,
 500,
 618,
 551,
 561,
 310,
 279,
 187,
 52,
 308,
 360,
 297,
 125,
 49,
 227,
 370,
 257,
 148,
 138,
 306,
 184,
 374,
 14,
 98,
 387,
 158,
 63,
 199,
 468,
 500,
 116,
 10,
 464,
 113,
 79,
 58,
 558,
 473,
 354,
 25,
 196,
 420,
 437,
 136,
 463,
 585,
 535,
 92,
 264,
 185,
 250,
 591,
 334,
 26,
 523,
 483,
 379,
 710,
 654,
 747,
 762,
 474,
 181,
 243,
 798,
 514,
 707,
 537,
 144,
 655,
 234,
 99,
 561,
 884,
 590,
 639,
 286,
 402,
 634,
 699,
 321,
 909,
 592,
 491,
 825,
 651,
 857,
 931,
 711,
 666,
 878,
 728,
 81,
 1,
 201,
 883,
 527,
 23,
 758,
 409,
 936,
 239,
 874,
 794,
 905,
 869,
 940,
 790,
 524,
 363,
 59,
 62,
 458,
 343,
 919,
 829,
 864,
 894,
 503,
 733,
 930,
 303,
 861,
 271,
 13,
 828,
 18,
 268,
 891,
 937,
 308,
 16,
 216,
 197,
 37,
 137,
 267,
 44,
 251,
 339,
 130,
 343,
 352,
 315,
 248,
 87,
 328,
 293,
 363,
 286,
 303,
 371,
 249,
 269,
 178,
 49,
 142,
 347,
 94,
 246,
 268,
 393,
 195,
 387,
 62,
 327,
 110,
 24,
 296,
 416,
 479,
 177,
 59,
 183,
 425,
 262,
 429,
 118,
 207,
 291,
 109,
 297,
 198,
 218,
 158,
 545,
 405,
 445,
 506,
 23,
 144,
 346,
 524,
 645,
 135,
 650,
 619,
 653,
 551,
 92,
 299,
 559,
 487,
 454,
 417,
 627,
 577,
 756,
 583,
 361,
 466,
 399,
 221,
 442,
 145,
 447,
 846,
 826,
 213,
 655,
 102,
 606,
 250,
 629,
 823,
 632,
 908,
 682,
 805,
 1,
 932,
 854,
 385,
 592,
 548,
 788,
 276,
 378,
 877,
 889,
 186,
 640,
 374,
 883,
 739,
 896,
 897,
 763,
 727,
 880,
 162,
 499,
 8,
 160,
 495,
 201,
 943,
 751,
 621,
 875,
 833,
 844,
 864,
 474,
 916,
 643,
 804,
 497,
 453,
 870,
 435,
 468,
 868,
 618,
 671,
 658,
 561,
 886,
 214]

In [26]:
Unique_userid_similar_item=set(similar_item_userid_single_list)

In [27]:
len(Unique_userid_similar_item)

371

In [28]:
#8. Input user watched movie_list
input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)

In [29]:
input_item_watched_userid

[63,
 1,
 90,
 9,
 79,
 409,
 18,
 486,
 198,
 568,
 181,
 662,
 76,
 537,
 590,
 924,
 655,
 773,
 707,
 870,
 806,
 828,
 524,
 936,
 758,
 71]

In [30]:
#9. Create a list which should have recom movieid to the input user
recom=[]
for per_id in Unique_userid_similar_item:
    if(per_id in input_item_watched_userid):
        pass
    else:
        recom.append(per_id)

In [31]:
len(recom)

345

In [32]:
sorted(recom)

[5,
 7,
 8,
 10,
 13,
 14,
 16,
 23,
 24,
 25,
 26,
 37,
 38,
 42,
 43,
 44,
 49,
 52,
 58,
 59,
 62,
 70,
 81,
 82,
 85,
 87,
 89,
 91,
 92,
 94,
 95,
 98,
 99,
 102,
 109,
 110,
 113,
 116,
 118,
 125,
 128,
 130,
 135,
 136,
 137,
 138,
 142,
 144,
 145,
 148,
 151,
 152,
 158,
 160,
 162,
 167,
 174,
 177,
 178,
 183,
 184,
 185,
 186,
 187,
 189,
 194,
 195,
 196,
 197,
 199,
 200,
 201,
 207,
 210,
 213,
 214,
 215,
 216,
 218,
 221,
 222,
 227,
 230,
 233,
 234,
 239,
 243,
 246,
 248,
 249,
 250,
 251,
 254,
 256,
 257,
 262,
 263,
 264,
 267,
 268,
 269,
 271,
 275,
 276,
 279,
 280,
 283,
 286,
 290,
 291,
 293,
 295,
 296,
 297,
 298,
 299,
 301,
 303,
 305,
 306,
 307,
 308,
 310,
 311,
 313,
 314,
 315,
 318,
 320,
 321,
 325,
 327,
 328,
 330,
 334,
 336,
 339,
 343,
 345,
 346,
 347,
 352,
 354,
 360,
 361,
 363,
 370,
 371,
 373,
 374,
 378,
 379,
 381,
 385,
 387,
 389,
 392,
 393,
 398,
 399,
 401,
 402,
 405,
 406,
 407,
 416,
 417,
 420,
 425,
 426,
 429,
 435,
 436,
 437,
 442,
 445,
 447,
 450,
 452,
 453,
 454,
 456,
 458,
 463,
 464,
 466,
 468,
 471,
 472,
 473,
 474,
 477,
 479,
 483,
 487,
 491,
 495,
 496,
 497,
 499,
 500,
 503,
 504,
 505,
 506,
 514,
 521,
 523,
 527,
 532,
 535,
 536,
 541,
 542,
 545,
 548,
 551,
 553,
 558,
 559,
 561,
 566,
 577,
 579,
 583,
 585,
 588,
 591,
 592,
 593,
 601,
 606,
 618,
 619,
 620,
 621,
 622,
 627,
 629,
 632,
 634,
 639,
 640,
 642,
 643,
 645,
 648,
 650,
 651,
 653,
 654,
 658,
 659,
 660,
 666,
 671,
 682,
 684,
 686,
 693,
 699,
 705,
 710,
 711,
 712,
 716,
 727,
 728,
 733,
 734,
 739,
 747,
 749,
 751,
 756,
 762,
 763,
 764,
 766,
 786,
 788,
 790,
 794,
 796,
 798,
 804,
 805,
 807,
 815,
 823,
 825,
 826,
 829,
 830,
 833,
 840,
 843,
 844,
 846,
 847,
 848,
 854,
 857,
 860,
 861,
 862,
 864,
 865,
 868,
 869,
 874,
 875,
 877,
 878,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 889,
 891,
 892,
 894,
 896,
 897,
 905,
 908,
 909,
 911,
 913,
 916,
 919,
 922,
 927,
 930,
 931,
 932,
 934,
 937,
 940,
 942,
 943]

In [33]:
# Cross Checking 
sorted(Unique_userid_similar_item)

[1,
 5,
 7,
 8,
 9,
 10,
 13,
 14,
 16,
 18,
 23,
 24,
 25,
 26,
 37,
 38,
 42,
 43,
 44,
 49,
 52,
 58,
 59,
 62,
 63,
 70,
 71,
 76,
 79,
 81,
 82,
 85,
 87,
 89,
 90,
 91,
 92,
 94,
 95,
 98,
 99,
 102,
 109,
 110,
 113,
 116,
 118,
 125,
 128,
 130,
 135,
 136,
 137,
 138,
 142,
 144,
 145,
 148,
 151,
 152,
 158,
 160,
 162,
 167,
 174,
 177,
 178,
 181,
 183,
 184,
 185,
 186,
 187,
 189,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 207,
 210,
 213,
 214,
 215,
 216,
 218,
 221,
 222,
 227,
 230,
 233,
 234,
 239,
 243,
 246,
 248,
 249,
 250,
 251,
 254,
 256,
 257,
 262,
 263,
 264,
 267,
 268,
 269,
 271,
 275,
 276,
 279,
 280,
 283,
 286,
 290,
 291,
 293,
 295,
 296,
 297,
 298,
 299,
 301,
 303,
 305,
 306,
 307,
 308,
 310,
 311,
 313,
 314,
 315,
 318,
 320,
 321,
 325,
 327,
 328,
 330,
 334,
 336,
 339,
 343,
 345,
 346,
 347,
 352,
 354,
 360,
 361,
 363,
 370,
 371,
 373,
 374,
 378,
 379,
 381,
 385,
 387,
 389,
 392,
 393,
 398,
 399,
 401,
 402,
 405,
 406,
 407,
 409,
 416,
 417,
 420,
 425,
 426,
 429,
 435,
 436,
 437,
 442,
 445,
 447,
 450,
 452,
 453,
 454,
 456,
 458,
 463,
 464,
 466,
 468,
 471,
 472,
 473,
 474,
 477,
 479,
 483,
 486,
 487,
 491,
 495,
 496,
 497,
 499,
 500,
 503,
 504,
 505,
 506,
 514,
 521,
 523,
 524,
 527,
 532,
 535,
 536,
 537,
 541,
 542,
 545,
 548,
 551,
 553,
 558,
 559,
 561,
 566,
 568,
 577,
 579,
 583,
 585,
 588,
 590,
 591,
 592,
 593,
 601,
 606,
 618,
 619,
 620,
 621,
 622,
 627,
 629,
 632,
 634,
 639,
 640,
 642,
 643,
 645,
 648,
 650,
 651,
 653,
 654,
 655,
 658,
 659,
 660,
 662,
 666,
 671,
 682,
 684,
 686,
 693,
 699,
 705,
 707,
 710,
 711,
 712,
 716,
 727,
 728,
 733,
 734,
 739,
 747,
 749,
 751,
 756,
 758,
 762,
 763,
 764,
 766,
 773,
 786,
 788,
 790,
 794,
 796,
 798,
 804,
 805,
 806,
 807,
 815,
 823,
 825,
 826,
 828,
 829,
 830,
 833,
 840,
 843,
 844,
 846,
 847,
 848,
 854,
 857,
 860,
 861,
 862,
 864,
 865,
 868,
 869,
 870,
 874,
 875,
 877,
 878,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 889,
 891,
 892,
 894,
 896,
 897,
 905,
 908,
 909,
 911,
 913,
 916,
 919,
 922,
 924,
 927,
 930,
 931,
 932,
 934,
 936,
 937,
 940,
 942,
 943]

In [34]:
# Cross Checking
sorted(input_item_watched_userid)

[1,
 9,
 18,
 63,
 71,
 76,
 79,
 90,
 181,
 198,
 409,
 486,
 524,
 537,
 568,
 590,
 655,
 662,
 707,
 758,
 773,
 806,
 828,
 870,
 924,
 936]

In [35]:
list(set(Unique_userid_similar_item)&set(input_item_watched_userid))

[1,
 773,
 9,
 524,
 655,
 18,
 662,
 409,
 537,
 924,
 806,
 936,
 181,
 568,
 828,
 63,
 707,
 198,
 71,
 76,
 590,
 79,
 90,
 486,
 870,
 758]

In [42]:
item_pred=pd.DataFrame(item_prediction,index=range(1, 944))

In [43]:
item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

In [44]:
item_pred[input_item]

1      0.446243
2      0.110883
3      0.083492
4      0.053374
5      0.232710
         ...
939    0.098578
940    0.162840
941    0.032761
942    0.164910
943    0.250015
Name: 6, Length: 943, dtype: float64

In [45]:
print(item_pred.index)

RangeIndex(start=1, stop=944, step=1)

In [48]:
# From recomd list select hightest rated film which would like by the user. Based on User prediction
highest_Rated=[]
input_item_pre=pd.DataFrame(item_pred[input_item])
input_item_pred=input_item_pre.T
for re in recom:
        value=input_item_pred[re].values
        if(value>=1):
            highest_Rated.append(re)

In [49]:
len(highest_Rated)

2

In [50]:
list(set(recom)&set(input_item_watched_userid))

[]

In [55]:
def itembased(input_item,item_similarity,item_predictions,similar_item_count,thres):
    #Convert the user_sim table into DataFrame
    item_sim_table=pd.DataFrame(item_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(similar_item_count).index
    #Convert in to list
    similar_item_input=list(similar_input_item) 
    #Using similar_user_input,can select movie id from ratings table
    similar_item_userid_list=[]
    for sim_item in similar_item_input:
        sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
        similar_item_userid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
    #Unique movieid from the list
    Unique_userid_similar_item=set(similar_item_userid_single_list)
    #Input user watched movie_list
    input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_userid_similar_item:
        if(per_id in input_item_watched_userid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(item_prediction,index=range(1, 944))
    input_item_pre=pd.DataFrame(user_pred[input_item])
    input_item_pred=input_item_pre.T
    for re in recom:
        value=input_item_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    highest_Rated
    return highest_Rated

In [56]:
Recommended_user=itembased(6,item_similarity,item_pred,5,0.8)

In [57]:
Recommended_user

[13, 276, 416, 450]